    image: docker:latest

    services:
        - docker:dind

    variables:
        DOCKER_DRIVER: overlay2

    build:
        stage: build
        before_script:
        - echo “$DOCKER_REGISTRY_PASS”
        - echo “$DOCKER_REGISTRY_USER”
        - echo “$DOCKER_IMAGE_NAME”
        - echo "$DOCKER_REGISTRY_PASS" | docker login --username $DOCKER_REGISTRY_USER --password-stdin
        script:
            - docker build --tag $DOCKER_IMAGE_NAME:latest . --file docker/dockerfile docker.io
            - docker push $DOCKER_REGISTRY_USER/$DOCKER_IMAGE_NAME:latest
