    image: docker:latest

    services:
        - docker:dind

    variables:
        DOCKER_DRIVER: overlay2
        DOCKER_IMAGE_NAME: $DOCKER_REGISTRY_USER/treeclust

    workflow:
        rules:
            - if: $CI_COMMIT_TAG
              when: never
            - if: $CI_COMMIT_BRANCH == 'main'

    build:
        stage: build
        before_script:
        - echo "$DOCKER_REGISTRY_PASS" | docker login --username $DOCKER_REGISTRY_USER --password-stdin
        script:
            - docker build --tag ${DOCKER_IMAGE_NAME}:$CI_COMMIT_SHA . --file docker/dockerfile
            - docker push ${DOCKER_IMAGE_NAME}:$CI_COMMIT_SHA
