# Base image
FROM python:3.8

WORKDIR /treeclust

# Add dependencies and channel information
COPY environment.yaml .

# Install base utilities for conda and opencv
RUN apt-get update \
    && apt-get install -y build-essential \
    && apt-get install -y wget \
    && apt-get install -y libgl1 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install miniconda
ENV CONDA_DIR /opt/conda
RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh && \
    /bin/bash ~/miniconda.sh -b -p /opt/conda

# Put conda in path so we can use conda activate
ENV PATH=$CONDA_DIR/bin:$PATH

RUN conda config --add channels conda-forge \
    && conda install mamba \
    && mamba env create -f environment.yaml

# Add files
COPY . .

CMD ["conda", "run", "-n", "treeclust", "python", "treeclust/__main__.py"]