# Base image
FROM python:3.8

WORKDIR /treeclust

# add req.txt
COPY requirements.txt .

# Install base utilities for conda and opencv
RUN apt-get update \
    && apt-get install -y build-essential \
    && apt-get install -y wget \
    && apt-get install -y libgl1 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install miniconda
ENV CONDA_DIR /opt/conda
RUN wget --quiet https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh && \
    /bin/bash ~/miniconda.sh -b -p /opt/conda

# Put conda in path so we can use conda activate
ENV PATH=$CONDA_DIR/bin:$PATH

RUN conda config --add channels conda-forge \
    && conda config --add channels pytorch \
    && conda install mamba pip \
    && pip install fuzzy-c-means \
    && ls \
    && mamba install --file requirements.txt

# Add files
COPY . .

CMD ["python", "treeclust/__main__.py"]