package:
  name: treeclust
  version: "1.0.0"

channels:
  - defaults
  - conda-forge

source:
  path: ..

build:
  number: 0
  preserve_egg_dir: True
  # script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - numpy
    - setuptools
  
  run:
    - python
    - numpy
    - pandas
    - scikit-learn
    - joblib
    - yellowbrick
    - geopandas
    - rioxarray
    - fiona
    - rasterio
    - tqdm
    - scipy
    - pytorch
    - torchvision
    - pillow
    - shapely
    - opencv
    - matplotlib
    - seaborn
    - scikit-image
    - umap-learn
  
  test:
    imports:
      - treeclust

  about:
    license: MIT
    license-file: LICENSE

    description:  Includes a automatic pipeline to evaluate the clustering capabilities of single tree crown images.
 